### ISSUE TITLE
Come up with an idea!

### ISSUE THREAD

**Issue by Mester** [Mester/demo-day-vikings#1]

**Comment by bdauer** [comment]
Ideas discussed so far:
1. Something with geo.
2. Something with Reddit.
3. Create book library based on pdf and epub files in directory, constructed by pulling data from google books or similar (too big).
4. Give us access to your tweets, we feed into a neural network and give a unique key to access a tweet generator that sounds like you.
5. Something related to tv/movies.

**Comment by jasonmeeks** [comment]
- Use APIs to find local events going on near you (concerts, comedians, sports, etc)
- Beer finder

**Comment by bdauer** [comment]
Anubhav was too lazy to add these, so I'm posting them on his behalf:

A Web app to show top 20 images of any #hashtag pulled from twitter imgur.com facebook instagram etc.

An app to get the lowest price of any product by scraping data from many online stores in a beautiful way.

**Comment by an00bhav** [comment]
Create a website to show some  characteristics of Countries. Any api for this?

**Comment by bdauer** [comment]
Idea I pitched on slack that I think would be simple enough: We get the top 10 for a user specified genre from here: https://www.reddit.com/r/listentothis/ .

**Comment by Mester** [comment]
Alright, it seems nobody was against @bdauer's  top 10 music idea, so it's been decided, that's what we're doing.
