### ISSUE TITLE
Design a basic frontend.

### ISSUE THREAD

**Issue by bdauer** [Mester/demo-day-vikings#14]
- [x]  Build a basic skeleton.
- [ ]  Add bootstrap.
- [ ]  Format with bootstrap.

**Comment by bdauer** [comment]
I'd like to take this. I don't have much experience with html/css except for parsing it.

**Comment by Mester** [comment]
Just a suggestion for structure on this. Might not be the best so if you figure out a better one, go for it.

Make a base html template that all pages will inherit from, with headers, navbars if any, etc etc. Then the main page html that extends the base and just adds the body content

**Comment by bdauer** [comment]
Good idea. I was thinking this would just be one page, but we'll at the very least have two pages: the landing page and a results page.

**Comment by Mester** [comment]
Yeah not sure how many pages we will need, but it's always a good idea to modularize as much as possible! Never know when we wanna expand with multiple pages or whatnot

**Comment by bdauer** [comment]
I'll be working on this tonight EST.
