### ISSUE TITLE
Get connected to the API

### ISSUE THREAD

**Issue by bdauer** [Mester/demo-day-vikings#15]
- [ ] Get an API key.
- [ ] Connect the app to the api
- [ ] Make the calls that we'll need.

**Comment by Mester** [comment]
Some sort of utility module might be a good idea for this so we don't have all the code in our views.

**Comment by jasonmeeks** [comment]
Currently only getting a short list of song names and the Genres are inconsistent. we need to find a way to get a longer list or find a different API request that will search the subreddit for specific genre names

**Comment by bdauer** [comment]
Did some googling and found this as an option to get everything from a subreddit (up to the 1000 post limit):

`<initial PRAW setup and shit>
sub = r.get_subreddit('your sub')
posts = sub.get_new(limit=None)
for x in posts:
    #do thing to each submission`

Not sure it'll work but if we focus on pulling more posts, we can deal with parsing the JSON files after. These are the steps that I would take:
- [ ] Fetch some posts (not all that we need, just to test.)
- [ ] Make sure that we're parsing the titles correctly.
- [ ] Figure out which data from the posts we need to hold onto. Create a data structure to hold it. Parse the posts into the data structure.
- [ ] Format the stored info for display on the site.
- [ ] Once it's working, make a fetch up to the limit and see if any new issues arise.

Some of those steps could break into smaller steps. There's probably more than one way to tackle the problem but that's how I'd do it in broad strokes.

**Comment by bdauer** [comment]
Also may want to make sure that we're only testing that the brackets contain the genre, since a lot of the times there's multiple keywords. And might be good to create test data once we know how the json is formatted. That way we'll get consistent results when we're trying to get it working. My 2c. Hope some of it's helpful.
