### ISSUE TITLE
Find and set up on a web host.

### ISSUE THREAD

**Issue by bdauer** [Mester/demo-day-vikings#18]
- [ ] Find a web host
- [ ] Get set up (this will very likely be multiple new issues.)

**Comment by jasonmeeks** [comment]
we can ask santiago for a digitalocean droplet to host our web app

**Comment by an00bhav** [comment]
What's the next action plan here? how did the meeting go?

**Comment by jasonmeeks** [comment]
https://www.youtube.com/watch?v=nAqrxIICgkE

Here's the video from the meeting. I was unable to attend, not sure who is working on this

**Comment by an00bhav** [comment]
I wasn't able to attend either, we can close this for now, as we know what needs to be done.
