### ISSUE TITLE
Decision Making and Moving Forward

### ISSUE THREAD

**Issue by bdauer** [Mester/demo-day-vikings#2]
Hey everyone.

So just in terms of advancing forward, I want to mention that we haven't thought about how we'll reach consensus on the issue of choosing a project.[1] Tyler, Jason and I have been discussing possibilities around some sort of top 10 music tracks app fetching from the /r/listentothis subreddit through the Reddit API. If we need to hash this out more, let's do that. If not, someone should raise a new issue for needed technologies (I don't want to be the one to do so because this was my idea and I have been involved in the discussion on Slack. Maybe someone who wasn't present, if in agreement can do so and if not, move the discussion around project ideas forward.)

For folks on the other side of the world, we should have a spec submitted within 24 - 36 hrs to fall around the deadline. 

[1] Without some general approach to making decisions, with 5 people this is going to get complicated.

**Comment by an00bhav** [comment]
Let's do it

**Comment by Mester** [comment]
The idea has been decided on. Closing this and moving the discussion of decision making to #4.
