### ISSUE TITLE
API module: get more post results

### ISSUE THREAD

**Issue by jasonmeeks** [Mester/demo-day-vikings#31]
Either need to page through the API request 20 at a time and fill up a database/list or consider seeing if there is a different API request where we can search the /r/ListenToThis subreddit for a specific genre. If we can't do that we probably need to populate a database with a ton of posts so we can hopefully have 10 of each genre

**Comment by jasonmeeks** [comment]
it might also be possible to get more than 20 results at once, need to try this as well

**Comment by jasonmeeks** [comment]
maybe it would be best to search /r/listentothis/new instead of /r/listentothis/hot and get the posts based on date posted rather than trending and then do our own algorithm to get the top 10 or random songs for each genre. im concerned if we decide to store in a database it might get complicated pulling from hot instead of new in terms of getting repeat data in the database (or we can just put code to prevent duplicate posts)

**Comment by tylerphillips55** [comment]
I agree. This seems more in line with our scope.
