### ISSUE TITLE
Help pick colors for the website!

### ISSUE THREAD

**Issue by bdauer** [Mester/demo-day-vikings#32]
I've chosen a handful of color palettes. Comment with any number of these palettes that you like or, if you don't like any, propose another!

http://www.colourlovers.com/palette/77121/Good_Friends

http://www.colourlovers.com/palette/444487/Curiosity_Killed

http://www.colourlovers.com/palette/90734/Newly_Risen_Moon

http://www.colourlovers.com/palette/903157/Entrapped_InAPalette

http://www.colourlovers.com/palette/475875/Gentle_Waves

http://www.colourlovers.com/palette/625987/dont_you_go_down

http://www.colourlovers.com/palette/1/metro

**Comment by tylerphillips55** [comment]
Curiosity Killed
