### ISSUE TITLE
To have a Post class or not to have a post class.

### ISSUE THREAD

**Issue by bdauer** [Mester/demo-day-vikings#43]
Let's weigh in here for better tracking.

**Comment by an00bhav** [comment]
Does this need any more discussion? Or should we close it?

**Comment by bdauer** [comment]
At this point it seems like we're moving forward without the post class. Let's give @jasonmeeks a chance to weigh in. He's online. He can close if there's nothing to discuss at that point.

**Comment by jasonmeeks** [comment]
We are currently using the post class on master, but it can be replaced with the DB once we get it set up if we want to go that route.

**Comment by an00bhav** [comment]
So we need to get rid of the post class!
