### ISSUE TITLE
Make the UI of the web app better. 

### ISSUE THREAD

**Issue by an00bhav** [Mester/demo-day-vikings#46]
I have created this mockup (pretty bad looking on paper). @jasonmeeks agrees with it, if anyone has better idea please suggest.

**Comment by Mester** [comment]
Is this still relevant?

**Comment by an00bhav** [comment]
The PR ( #69  ) that you are working on, the html-remodelling, once merged in master, will address this. Then it will be fixed

**Comment by Mester** [comment]
Oh right, my bad :P
