### ISSUE TITLE
Change the name of `my_app` to something better, as it is a module

### ISSUE THREAD

**Issue by an00bhav** [Mester/demo-day-vikings#50]
my_app directory now contains all the important api related to the app, we need to change the name of the directory to something meaningful. 

Points to discuss, 

1) Does this make sense? 
2) What does it impacts? setup.py? tox.ini?

**Comment by Mester** [comment]
My question is, does it really matter right now? Or at least important enough to prioritize over the other stuff that needs to be done? (Also we aren't really using setup.py or tox.ini and probably won't be by the time deadline is up) (I am also aware of the fact that this could've been changed and done in the time it took me to write this lol)

**Comment by an00bhav** [comment]
It doesn't matter right now, but we can create a bug, with a low priority.

**Comment by Mester** [comment]
I was just thinking it might be unnecessary because that folder name won't really be seen by anyone other than us and we only have one module. If we had multiple modules then yeah definitely

**Comment by an00bhav** [comment]
I was thinking more from a moduling point of view. You see all our imports will be 

```
from my_app import settings.py
```

to 

```
from music_app import settings.py
```

It's about etiquette. It's hardly a matter of 2 mins to make the change. I'll do it.

**Comment by Mester** [comment]
Ok sounds great!
