### ISSUE TITLE
Ditch oAuth/reddit api and make requests directly to /r/subreddit.json

### ISSUE THREAD

**Issue by tylerphillips55** [Mester/demo-day-vikings#52]
This seems like a better alternative. There doesn't seem to be a limit to the number of results we can get (as with the api) and even more, it eliminates the need for a config.py (as @neo1691 pointed out). We'd have to rewrite some of our code. Also, there isn't a limit on the number of results per request. Thoughts?

**Comment by an00bhav** [comment]
+1.

Lets get rid of client id and client secret in config. For all other actual
config we can use settings.py
