### ISSUE TITLE
Are we still using a database? If so, let's decide on one.

### ISSUE THREAD

**Issue by bdauer** [Mester/demo-day-vikings#55]
I was thinking MongoDB might be a good way to go. We can store the JSON data and not worry about too much. As I'm looking at it, we don't need a lot of linked tables.

**Comment by an00bhav** [comment]
Right now we are only making the api call or the json call, which takes it's own sweet time depending on the network, parses it, and then shows it on the UI. 

We should be having a class to periodically fetch new posts from /r/listentothis, update any upvotes count if required and insert in to the the data. 

The UI should only show what is in the database.

These two tasks are independent of each other.

**Comment by bdauer** [comment]
As I'm getting back up to speed I see we already have a sql table being created. Just not doing anything with it yet. I'm going to close this, create separate issues for those tasks and get started on tests.

**Comment by an00bhav** [comment]
Great.
