### ISSUE TITLE
Replace Post class with multiple functions.

### ISSUE THREAD

**Issue by bdauer** [Mester/demo-day-vikings#64]
- [ ]  Get JSON file from API
- [ ] Add JSON file to db
- [ ] Parse JSON file from the db instead of from the API.
- [ ] Run in the background at a regular interval and append new posts to the database.

**Comment by tylerphillips55** [comment]
Removing and replacing the post class will be simple. The question is what should we replace it with? If we care about search speed, a dictionary is faster. However, the fastest would be named tuples.

**Comment by tylerphillips55** [comment]
On second thought, if we've already entered the json-encoded data into the db and are merely pulling data out that matches the criteria, it wont make much of a difference as the "search" would have been essentially done. All results in the collected results will be given. Search speed is not much of an issue. On the discussion of memory, dictionaries and named tuples aren't much different I believe.

**Comment by tylerphillips55** [comment]
Never mind, just saw your post about tinydb. So yes, it does matter.

**Comment by an00bhav** [comment]
@tylerphillips55 The new branch dev has the code for this. Check it out.
