### ISSUE TITLE
Need to be under the rmotr group.

### ISSUE THREAD

**Issue by bdauer** [Mester/demo-day-vikings#8]
Hey guys,

We need to have our project under the rmotr group according to the spec. Not sure how we make that work on github. Will look into it later if I have time but I have a feeling @Mester can git it done before I do.

**Comment by Mester** [comment]
Asking Santiago/Martin about this if it's needed. If it is, can't be done without them anyway, need admin access to the organization.

**Comment by an00bhav** [comment]
We should really think about changing the name of this repository. Closing it for now.
