### ISSUE TITLE
Add'l features?

### ISSUE THREAD

**Issue by bdauer** [Mester/demo-day-vikings#9]
So at this point the app takes a genre name and searches for it. Anything else we might want to add? e.g. we could save all music from a user's searches or keep a history of all of the music that they've actually played (I like the latter idea).

**Comment by Mester** [comment]
You're thinking a bit ahead of time :P. I think we just focus on the basic thing we said, (simple top10 from the subreddit I think it was) and polish. Then after consider extras if we have extra time.

**Comment by bdauer** [comment]
There's a section in the spec where we list out all features and a separate one for general overview of the app. Made me think we might want to mention more than one. But I agree, if we can get away with listing only the one feature, it would be better to go beyond the spec if there's time than not to meet it.

**Comment by Mester** [comment]
Yeah it's fine to just do one thing. Or we could just do like "features: top10, extra features in case of extra time: feat123"

**Comment by bdauer** [comment]
If you're proposing the latter, I'll second it.
